# Generated by Django 5.2.12 on 2026-04-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='alert_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='is_alert',
            field=models.BooleanField(default=False),
        ),
    ]
